name: Build android app

on:
  push:
  workflow_dispatch:

jobs:
  # Build App
  build:
    runs-on: windows-latest
    
    env:
      APPLICATION_NAME: MCE_API_SERVER
      
    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2


      - name: Create and Sign the APK
        run: msbuild ${{ env.APPLICATION_NAME }}.csproj /p:Configuration=Release /p:OutputPath=bin\Release\

      - name: List folder content
        run: dir ${{ env.APPLICATION_NAME }}\bin\Release

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyApplication.apk
          path: ${{ env.APPLICATION_NAME }}\bin\Release\${{ PACKAGE_NAME }}-Signed.apk
